services:
  postgres:
    image: 'postgres:latest'
    environment:
      - '${POSTGRES_LOCAL_PORT}:${POSTGRES_DOCKER_PORT}'
      - 'POSTGRES_DB=cash_goals'
      - 'POSTGRES_PASSWORD=qwerty'
      - 'POSTGRES_USER=user'
    ports:
      - '5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
