spring:
  graphql:
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
  sql:
    init:
      mode: always