spring:
  profiles:
    active: dev
  graphql:
    graphiql:
      enabled: true
  config:
    import: optional:file:.env[.properties]
  application:
    name: cashgoals
  datasource:
    username: ${POSTGRES_USER:#{user}}
    password: ${POSTGRES_PASSWORD:#{password}}
    url: ${POSTGRES_URL}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  security:
    jwt:
      public-key: classpath:jwt/app.pub
      private-key: classpath:jwt/app.key
      access-expiration-in-hours: ${JTW_EXPIRATION_IN_HOURS}
      refresh-expiration-in-days: ${JTW_REFRESH_EXPIRATION_IN_DAYS}
  data:
    redis:
      database: ${REDIS_DATABASE}
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: ${REDIS_TIMEOUT}
      url: redis://${REDIS_HOST}:${REDIS_PORT}
