spring:
  main:
    lazy-initialization: true
  graphql:
    schema:
      printer:
        enabled: true
    graphiql:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always