name: Build and test spring gradle application

env:
  MYSQL_USER: user
  MYSQL_PASSWORD: password
  MYSQL_URL: jdbc:mysql://localhost:${MYSQL_LOCAL_PORT}/${MYSQL_DATABASE}

on:
  push:
    branches: [ ma ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB=${POSTGRES_DATABASE}
          POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
          POSTGRES_USER=${POSTGRES_USER}
        ports:
          - 5432:5432
      rabbitmq:
        image: rabbitmq:management
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
          - 15672:15672
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17-ea'
          distribution: 'temurin'
          cache: maven
      - name: Build backend application
        run: ./gradlew build --no-daemon
      - name: Run production backend application
        run: ./gradlew bootRun --args='--spring.profiles.active=prod' --no-daemon